### ISSUE TITLE
Update GeoSteiner version breaks this wrapper

### ISSUE THREAD

**Issue by leethargo** [leethargo/geonet#1]
Apparently the new version 5.0 of the external [GeoSteiner](www.geosteiner.com) software has a slighty different output format which breaks the `subprocess` based wrapper here.

Probably easy to fix by relaxing the keywords matched in `parse_ps`.

**Comment by leethargo** [comment]
I looked at the manual of GeoSteiner today. It would probably be easier to just look for the lines containing the `@C`, where the positions of the Steiner nodes are listed. From these, the Steiner tree could be recovered as a minimum spanning tree.

**Comment by rschwarz** [comment]
Fixed with #2 and 3aa198.
